management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus" # health, info, loggers, metrics
  endpoint:
    health:
      show-details: always
    shutdown:
      access: none
logging:
  level:
    root: info
    org:
      springframework: warn
      boot: error
      data:
        redis: debug
  pattern:
    console: '%n %d{HH:mm:ss} | %highlight(%-5level) | %cyan(%logger{30}) | %msg'

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    enabled: ${SWAGGER_ENABLE:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLE:false}
    path: ${SWAGGER_URL:/docs}

spring:
  output:
    ansi:
      enabled: always
  aop:
    auto: true # When you don't need logging.
  banner:
    location: classpath:banner/banner.txt
  main:
    banner-mode: console
